TARGET := iphone:clang:latest:7.0


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AccountsdHelper

AccountsdHelper_FILES = Tweak.x
AccountsdHelper_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk